### ISSUE TITLE
key modifier or other key to open link in new tab

### ISSUE THREAD

**Issue by jlxz** [gggritso/Vimmy.safariextension#1]
it would be great to be able to open a link in a new tab instead default webpage/safari behavior. For example, pressing f will open using default behavior, but if you press ⇧+f it will force opening url in a new tab (preferable background tab) . Another possibility would be using always f to select links but if you keep pressed some modifier key (e.g. ⌘, ⌥) while typing the two letters to select a link, it would open the link in a new tab.

I've tried all vim-like safari extensions, I always end coming back to yours, it's the best.

**Comment by gggritso** [comment]
Sorry it took three years, I forgot this project exists. I just shipped out a brand-new version, where ⇧+f will force a new tab. I’m submitting to the store, but in the meantime you can download the bundle off my [S3 bucket](https://s3.amazonaws.com/gggritso.com/Vimmy.safariextz).

Cheers!
