### ISSUE TITLE
Element hints cut off at top of websites

### ISSUE THREAD

**Issue by hadiskeini** [gggritso/Vimmy.safariextension#10]
The element hints that appear when 'f' is pressed get cut off by the safari title bar when the element is at the top of the website. See [reddit.com](https://www.reddit.com) for a good example.

**Comment by gggritso** [comment]
In `0.4.0` I will bump the threshold that switches the labels to appear on the right. Here is what Reddit will look like:

![screen shot 2016-09-25 at 4 16 03 pm](https://cloud.githubusercontent.com/assets/989898/18817973/72c8a708-833b-11e6-9ef9-0db1753afcf9.png)
