### ISSUE TITLE
Add version to the extension update url

### ISSUE THREAD

**Issue by jostyee** [gggritso/Vimmy.safariextension#19]
e.g. https://github.com/kaishin/Nope/blob/master/updates.plist
in this way we can avoid downloading old version via Safari Extensions Gallery, currently I can only install v0.2 from it.

**Comment by gggritso** [comment]
Totally my bad for doing this incorrectly. Thank you for the example, I will set this up later this week when I cut `0.7.0`.

**Comment by gggritso** [comment]
I posted a new update manifest file, and I got the `0.7.0` update successfully, so I’m going to close the issue. Thanks again!
