### ISSUE TITLE
some suggest

### ISSUE THREAD

**Issue by shanlanmi** [gggritso/Vimmy.safariextension#2]
I like you tag style when pressing `f` key. 
It will be awesome if it has a short key for go to next tab.
forgive my poor English :)

**Comment by gggritso** [comment]
Vim has a few tab navigation options, which ones are you interested in? `gt` and `gT`?

**Comment by shanlanmi** [comment]
I have used chrome for a long time, the Vimium in chrome is great.
There are two ways to go tab in chrome, `gt, gT` and `K, J`,  I prefer the `K, J` way.

**Comment by iFwu** [comment]
I'd like use q and w to switch between tabs (left or right tab).

**Comment by shanlanmi** [comment]
ok，`q` and `w` is great too，I just don't like press two key to move tab（like `gt`）

**Comment by gggritso** [comment]
I understand that typing two keys is annoying, but I don’t want to implement too many shortcuts that are different from Vim behaviour. `gt` and `gT` is how Vim does it, and that’s what I’ll add. I’m currently testing the feature locally, and I’ll release an update once I feel that it’s stable.

**Comment by gggritso** [comment]
The build with `gT` and `gt` support has been uploaded and should be available soon.
