### ISSUE TITLE
Apple Safari Extensions Gallery only provide version 0.2 

### ISSUE THREAD

**Issue by hexid26** [gggritso/Vimmy.safariextension#20]
The first, thank you for the greatest extension on Safari.

I can only get Vimmy 0.2.0 from Safari Extensions Gallery.
After checking the github website and I knew the latest version is 0.7.0...

So, is it possible to replace the old version on Safari Extensions Gallery?
I read closed issue and found a link to get the version 0.6.0....^_^

**Comment by gggritso** [comment]
Good call, sorry about that! I re-submitted to the Extensions Gallery with version 0.7.0. I’ll let you know when I hear back. I’m also going to put in a patch soon that updates from the gallery itself, rather than from GitHub.

**Comment by gggritso** [comment]
I actually still haven’t heard back from Apple for some reason. I’ll re-submit again and see what happens.

**Comment by hexid26** [comment]
Thanks for your work and patience. It looks like Apple take a long time to accept. 
You can add a download link in 'README.md' file as a temporary solution.

**Comment by gggritso** [comment]
I still haven’t heard from Apple. In the meantime I added a download link like you suggested.

**Comment by steve-jokes** [comment]
A great job, mate. 
Looking forward to receive your update

**Comment by horak** [comment]
Looks like this can be closed now! This is awesome @gggritso.

**Comment by jostyee** [comment]
Safari Extensions Gallery has only outdated v0.7.0

**Comment by horak** [comment]
Yes, but it no longer contains just v0.2 – which the title indicates.

**Comment by gggritso** [comment]
Fair. Apple have updated the version without telling me. I have also submitted an update for 0.7.1. I’m closing the issue for now. Thanks everyone!
