### ISSUE TITLE
 建议直接把 Cvim 的代码 copy过来

### ISSUE THREAD

**Issue by vipheyue** [gggritso/Vimmy.safariextension#22]
站在巨人的肩膀上还是有优势的

**Comment by jostyee** [comment]
@gggritso nonsense issue, you can just close it.

**Comment by vipheyue** [comment]
Suggest  to thecopy the Cvim code directly.
Standing on the shoulders of giants still have an advantage

**Comment by gggritso** [comment]
I agree with the sentiment, but there’s room for more than one Vim binding plugin on Safari. Porting extensions over is fairly straight-forward, so it makes more sense to contact Cvim developers for a Safari port than to open an issue here.
