### ISSUE TITLE
Add option to make links not on an angle?

### ISSUE THREAD

**Issue by danielcompton** [gggritso/Vimmy.safariextension#23]
I find the angled chevrons hard to read. It would be handy if there was an option to have them flat, rather than on an angle.

**Comment by gggritso** [comment]
Ah, really? Damn! The reason the chevrons are at an angle is because for dense (i.e. many) websites, having just horizontal chevrons causes a _lot_ of overlapping chevrons, and then it’s actually impossible to read them at all if there are many links. Does this happen for you? Is it better to have horizontal chevrons?

**Comment by ChrisLTD** [comment]
I actually prefer the horizontal chevrons for readability as well... I even created my own stylesheet for them that look like Vimium.

![screen shot 2017-01-03 at 11 01 35 am](https://cloud.githubusercontent.com/assets/157232/21613626/0885ce04-d1a4-11e6-92fc-3947acb49653.png)


```
#vimmy-hints {
	position: absolute !important;
	left: 0 !important;
	right: 0 !important;

	z-index: 2147483646									!important;
}

#vimmy-hints span {
	height: 16px										!important;
	box-sizing: border-box								!important;

	position: absolute									!important;
	float: none !important;

	font-family: "Courier New", "Courier", monospace 	!important;

	font-size: 13px										!important;
	line-height: 13px									!important;

	background-color: #FFC300  								!important;
	color: black !important;
	opacity: 0.85		!important;
	border: none										!important;

	border-radius: 3px									!important;
	padding: 1px 5px 0px 5px							!important;

	letter-spacing: 1px									!important;

	transition: opacity 0.2s !important;
}

#vimmy-hints span.ineligible {
	opacity: 0.1 !important;
}

#vimmy-hints span.accepted {
	color: #27ae60 !important;
}

#vimmy-hints span b {
	display: inline										!important;
	font-weight: bold									!important;
	-webkit-font-smoothing: subpixel-antialiased		!important;
	color: inherit										!important;

	vertical-align: top;
 
	font-family: inherit !important;
	font-size: 13px										!important;
	line-height: 13px									!important;
	padding: none										!important;
	margin: none										!important;
    text-shadow: 1px 1px 0 rgba(255,255,255,.5)       !important;
}

#vimmy-hints span b.typed {
	color: #c0392b											!important;
}

/*#vimmy-hints span.left {
	transform: rotate(20deg);
}

#vimmy-hints span.right {
	transform: rotate(20deg);
}*/

#vimmy-hints span:before,
#vimmy-hints span:after {
	content: ""													!important;

	position: absolute											!important;
	top: 1px													!important;

	width: 0													!important;
	height: 0													!important;

	border-style: solid												!important;
	border-width: 7px 7px 7px 7px								!important;
}

#vimmy-hints span.left:after {
	right: -12px													!important;

	border-color: transparent transparent transparent #FFC300		!important;
}

#vimmy-hints span.left:before {
	display: none;
}

#vimmy-hints span.right:before {
	left: -12px												!important;

	border-color: transparent #FFC300 transparent transparent		!important;
}

#vimmy-hints span.right:after {
	display: none;
}
```

**Comment by gggritso** [comment]
@ChrisLTD what extension do you use for that stylesheet? Is it pretty straight-forward to use? If so, maybe this is something that should be done in user-land, rather than me making this decision for everyone. Otherwise, I could make chevron rotation an option (but I’d rather not, to be honest).

**Comment by andyw8** [comment]
+1 for using horizontal labels (or making this an option)

**Comment by ChrisLTD** [comment]
@gggritso I forked your extension and added it myself. Not for the faint of heart! I can try and see if I can add a switch option and do a pull request.

**Comment by KenjiTakahashi** [comment]
If anything, please make it optional. I like the angled ones better :-).

**Comment by gggritso** [comment]
This is addressed in PR #25. If you’re interested in beta-testing it, [please give it a go](https://github.com/gggritso/Vimmy.safariextension/files/691785/Vimmy.0.8.0.safariextz.zip), I’d appreciate it. Otherwise I will test it locally for a few days and cut a build early next week.

**Comment by ChrisLTD** [comment]
@gggritso not sure if it's just me, but when I installed it, the rotation setting checkbox wasn't checked. So in order to un-rotate them, I had to check it, reload, and then uncheck it.

**Comment by andyw8** [comment]
Thanks for this @gggritso. I the same issue as @ChrisLTD, the initial state seems incorrect.

**Comment by gggritso** [comment]
New 0.8.0 release candidate is [now available](https://github.com/gggritso/Vimmy.safariextension/files/692488/Vimmy.0.8.0.safariextz.zip). It also has two new small features:
- pressing `ESC` while in an input field brings focus to the body (useful for filling out forms)
- activating radio and checkbox elements with the keyboard actually checks them off instead of just selecting them
