### ISSUE TITLE
Version 0.7.1 shows as 0.7.0

### ISSUE THREAD

**Issue by KenjiTakahashi** [gggritso/Vimmy.safariextension#24]
I've downloaded the latest version from https://github.com/gggritso/Vimmy.safariextension/releases/tag/0.7.1, but Safari shows it as 0.7.0. It also shows that there's update available, but hitting the "Update" button seems to do nothing.

**Comment by gggritso** [comment]
Ugh. Apple Extension distribution is a PITA. I’m seriously considering just taking it off the store. I’ll submit another update. I do not even get an option to update.

**Comment by gggritso** [comment]
Version 0.8.0 has been released, with repaired `updateManifest.plist` and `Info.plist` files, which should take care of this. Sorry, and also closing for now.
