### ISSUE TITLE
J and K for previous/next tab

### ISSUE THREAD

**Issue by cocevk** [gggritso/Vimmy.safariextension#26]
It would be really nice if - besides gt and gT (which are kind of hard to press) - J and K would be supported for  previous and next tab.

**Comment by gggritso** [comment]
Is there precedent for this? Does Vimium do this? Do those keys have a similar meaning in Vim?

**Comment by cocevk** [comment]
Yes, @gggritso, Vimium does this.

**Comment by cocevk** [comment]
Thanks, @gggritso ! 👍
