### ISSUE TITLE
Smooth scrolling with hjkl

### ISSUE THREAD

**Issue by trishume** [gggritso/Vimmy.safariextension#28]
Currently scrolling by holding down hjkl scrolls in jerks every time the key repeat is triggered. Vimium has a feature that smooths this out so that when you scroll by holding down a key the scrolling is smooth. It would be nice to have this in Vimmy.

@gggritso

**Comment by gggritso** [comment]
I’ll give that a serious think, though holding down keys is not exactly Vim-like ;)

**Comment by net** [comment]
If you want vim-like behavior, you should allow numbers to repeat actions. E.g. `5j` should scroll down 5 times. I agree that Vimium's scrolling is very nice though, and I'd too would love to see it in Vimmy.

**Comment by gggritso** [comment]
I will work on this, unless someone else would like to tackle it. If not, I’ll probably carve out some time next weekend to get this done.

**Comment by gggritso** [comment]
In light of #41 I’m going to close this. I was going to work on this functionality but it’s quite a lot of trouble, and I think that the key repeat implementation covers this much better. If anyone submits a PR for this feature I’ll be happy to look it over, though!
