### ISSUE TITLE
Disable reload of page when "r" is typed in a select tag

### ISSUE THREAD

**Issue by mrknmc** [gggritso/Vimmy.safariextension#29]
Currently, typing "r" in a select tag to scroll to value that starts with "r" reloads the page. I think the behaviour here should be equivalent to typing "r" in a text area or input field which doesn't trigger the reload. Happy to submit a PR for this.

**Comment by gggritso** [comment]
You’re absolutely right, of course. Thank you for the PR! I will release `0.8.1` with the fix later this week.
