### ISSUE TITLE
Typing 'r' reloads page in some web forms after loosing focus

### ISSUE THREAD

**Issue by decayofmind** [gggritso/Vimmy.safariextension#31]
Hi!

Simply try to type something with 'r' letter even in GitHub search form to make page reloads.

I'm using **vimmy 0.7.0**

**Comment by rubenvarela** [comment]
Just noticed this on https://tools.pingdom.com

Besides refreshing on `r`

- it wouldn't let me insert `h`,`j`,`k`,`l`. 
- `g` causes a Page Up
- `t` is inserted, but _sometimes_ it changes the tab to the next one. Not sure what else triggered that.
- `x` gets inserted and then the tab closes (my machine is under heavy load right now, so it's a bit slow to respond and I see the letter being inserted).

Safari - 10.0.1 (11602.2.14.0.7). 
OS X El Capitan -  10.11.6 (15G1108)
Vimmy - 0.7.0

**Comment by rubenvarela** [comment]
Just saw Issue #32 I will try upgrading later today. 

@decayofmind, Just in case you haven't seen it either, there's a new release, https://github.com/gggritso/Vimmy.safariextension/releases 

Don't know if it displays the same issue though.

**Comment by rubenvarela** [comment]
@gggritso Thank you for being quick!

Regarding your comment,

> Add more input types to capturables.
> I will eventually need a better way to manage this, but for now this is fine. Closes #31

Just in case it's any help, VimFX, Vimium and Vimperator basically do it the same way.

VimFX, 
- https://github.com/akhodakivskiy/VimFx/blob/master/extension/lib/utils.coffee#L166

Vimium,
- https://github.com/philc/vimium/blob/master/content_scripts/vimium_frontend.coffee#L24

Vimperator, 
- https://github.com/vimperator/vimperator-labs/blob/master/common/content/buffer.js#L1670
- https://github.com/vimperator/vimperator-labs/blob/master/common/content/events.js#L697

That last line on Vimperator, does seem to have a few more that you might be interested in.

Vimium, on [Line 20](https://github.com/philc/vimium/blob/master/content_scripts/vimium_frontend.coffee#L20), references HTML5's date picker.
Safari doesn't have support for it yet, http://caniuse.com/#search=input%20date
But it seems to be in WebKit, https://bugs.webkit.org/show_bug.cgi?id=29359

**Comment by gggritso** [comment]
Very interesting! I think my overall question is whether I should just ignore Vimmy commands on _all_ inputs. Is there any harm in that?

**Comment by rubenvarela** [comment]
I see what you mean. I can't think of anything right now. The only thing is getting stuck on a field. Specially on a website that forces the focus on page load (like on the pingdom link above).

Would it be possible to add a behavior so pressing `Esc` while an input field has focus, will get the user out of the field?

Similar to pressing `Esc` on link mode?

**Comment by gggritso** [comment]
That was added in `0.8.0` actually :)

**Comment by rubenvarela** [comment]
😅 Updated and just tried it. It works great.

I don't see any issue right now that couldn't be solved. You can always leave a field and regain focus by using a hint `f`.
