### ISSUE TITLE
Fix "Latest Release" in README.md

### ISSUE THREAD

**Issue by cocevk** [gggritso/Vimmy.safariextension#32]
README.md contains the following:

The best way to get the latest version is to download the release file from GitHub. 

The link points to v0.7.0:
https://github.com/gggritso/Vimmy.safariextension/releases/download/0.7.0/Vimmy.safariextz
it should probably point here (if you don't want to modify on each release): 
https://github.com/gggritso/Vimmy.safariextension/releases
or here:
https://github.com/gggritso/Vimmy.safariextension/releases/download/0.8.0/Vimmy.safariextz

**Comment by rubenvarela** [comment]
I know this was just closed, but another option is `/releases/latest`, https://github.com/gggritso/Vimmy.safariextension/releases/latest

**Comment by gggritso** [comment]
@rubenvarela that’s perfect, thank you!
