### ISSUE TITLE
Can't Install from Safari Extension Gallery

### ISSUE THREAD

**Issue by sethfri** [gggritso/Vimmy.safariextension#33]
Every time I try to install from the Safari Extension Gallery, I get

**Safari can't install this extension**
An error occurred while installing this extension.

**Comment by sethfri** [comment]
My Safari was in a bad state I guess. Rebooting solved this

**Comment by gggritso** [comment]
Weird, but okay!

**Comment by sethfri** [comment]
Agreed that it's weird, but while Googling, I saw several others have this issue with various other extensions, so it's not just Vimmy (fortunately for you, but bad for those of us who have no idea what the real root cause is...)
