### ISSUE TITLE
Open in new tab and foreground that tab

### ISSUE THREAD

**Issue by horak** [gggritso/Vimmy.safariextension#37]
I find myself very often opening a tab in the background and then navigating to it immediately thereafter. Would this be handy for anyone else?

**Comment by gggritso** [comment]
Hm ... in a way that’s different from using `shift+f`?

**Comment by gggritso** [comment]
Hmm, so the opposite of how `shift+f` works?

**Comment by horak** [comment]
Yeah, that's what I was thinking. Nine times out of ten I use 'shift+f' and then navigate one tab over immediately after.

**Comment by gggritso** [comment]
Any thoughts on what key combo might work for this?

**Comment by ChrisLTD** [comment]
I use the background tab feature to open a bunch of tabs off a common page, like a search engine result page, then check each result one by one. If this becomes a feature, I think it should either be a new key combo, or a setting.

**Comment by gggritso** [comment]
A setting as in, a setting that changes `shift+f` behaviour to immediately focus on the new tab? I feel good about that option.

**Comment by ChrisLTD** [comment]
Yeah, that's what I meant. Sorry for being unclear.

**Comment by horak** [comment]
Oh, I think both should be available. Maybe `shift+f` and `shift+b` as defaults, standing for foreground and background.

**Comment by gggritso** [comment]
Fair, but I can't remap `shift+f` to a new command at this point, too many people (myself included) have gotten used to that opening in the background.

**Comment by horak** [comment]
I completely get that. How about `shift+j` then. It sits below the other pointer finger.

**Comment by gggritso** [comment]
That moves to the previous tab :)

**Comment by dwaxe** [comment]
Is it possible to make it follow the Safari preference? Preferences > Tabs > "When a new tab or window opens, make it active"

**Comment by gggritso** [comment]
I was thinking the same thing, I need to look into that. I kind of doubt that Safari exposes user preferences, but it’s worth a look.

**Comment by gggritso** [comment]
I couldn’t find a way to read the user’s preferences, but I do have a patch that adds an extension setting to force new tabs to be activated. Unless there are serious objections, I will merge it in the next few days.

**Comment by gggritso** [comment]
Added to 0.9.0.

**Comment by niksosf** [comment]
Thanks for this awesome extension!

Maybe I am in the minority that prefers having tabs open in the background. For example, if I were searching for a product on Amazon, I would want to open the individual product's page in the background as I scroll down; then I go through the tabs. 

Is there any plans on having a toggle to enable/disable background tab link opening?

Thanks a bunch

**Comment by gggritso** [comment]
You mean by default, rather than by holding `shift+f`?
