### ISSUE TITLE
A key mapping suggest

### ISSUE THREAD

**Issue by Leon-S** [gggritso/Vimmy.safariextension#38]
Hi, gggritso, I really love your Vimmy.
But here I want to make a suggest that can you map the q button as to break out of the link mode?
Because the esc and ctrl-[ is much more hard to reach.
(I know the Vim tradition of using Esc and ctrl-[ and respect that .)
What do you think?

**Comment by Leon-S** [comment]
go back in history key can also be mapping on the q button .

**Comment by gggritso** [comment]
I don’t love this idea, mostly because during link mode, all letter keys are locked to be used for hints. In the future I’m pretty likely to make the set of keys that’s used for hints customizable, and I don’t want to make any exceptions. What if I let backspace also break out of link mode?

**Comment by gggritso** [comment]
The change I proposed will be added to a future build sometime soon. I’m closing this for now, since I believe my solution covers this adequately.
