### ISSUE TITLE
o For search bar

### ISSUE THREAD

**Issue by EntilZha** [gggritso/Vimmy.safariextension#4]
It would be neat if pressing `o` would open a search bar like Vimium does in Chrome

**Comment by dbmrq** [comment]
Afaik `o` is for a sort of address bar in Vimium, and `/` is for searches, but yes, both would be great.

I think maybe `:` would make a little more sense for the address bar, vimwise. and `/` would be like `cmd-f`.

**Comment by gggritso** [comment]
So, to your mind, should `/` just trigger the built-in search? I’m not too jazzed about trying to write my own search for pages, but just triggering the built-in search seems like a pretty quick win.

As a sidenote, there’s a problem in Safari right now where triggering the search removes focus from the page, and the key bindings stop working. I’m trying to figure out a way to overcome that, but with little luck so far.

**Comment by dbmrq** [comment]
Well, ideally the search would have to be a lot different, so we'd be able to use `n` and `N` and so on… but I agree that it's not worth the effort to write a search feature from scratch. So for now I think it's enough to just make the built-in safari shortcuts more vim-like; `/` would just trigger the built-in search and `:` would be the same as `<cmd-L>`.

Great work here, btw. You should add a paypal donation thing or something, I'd buy you a ~~beer~~ cider. :)

**Comment by EntilZha** [comment]
I was thinking that it would be convenient to focus the address bar since it serves a similar purpose to the address bar in Vimium. Would be a way to avoid having to take hands off keyboards to go to a new url or search for something

**Comment by gggritso** [comment]
Unfortunately this might be impossible. The Safari API for extensions controlling the browser is pretty limited, and I don’t see a good way to control the browser in this way. Any suggestions?

**Comment by dbmrq** [comment]
Is it impossible to just remap `:` to `<cmd-L>` and `/` to `<c-f>`?

**Comment by gggritso** [comment]
So that’s my question to you, remap at what level? The extension is just a JavaScript script that runs inside every page. I would need to listen to keyboard events and somehow emit different ones. There is an API to trigger key events, but they don’t bubble up to the browser, which I assume would be a _huge_ security risk. Imagine I could trigger JS from the page that fires browser events!

**Comment by dbmrq** [comment]
Ah, I see. Maybe it could be done with the acessibility api, but it's beyond the scope of an extension I guess. There might be a way to do it with hammerspoon, I'll look into it when I have the time and post the script here if I work it out, then it could be used along with Vimmy.

**Comment by EntilZha** [comment]
Would it be possible to bring up a window/textbox with `o` and upon entering that it will forward it to the address bar in some way (I am unfamiliar with what APIs are available)?

**Comment by gggritso** [comment]
That’s possible (though it wouldn’t be very nice-looking) but I also think it would be somewhat weird because I’d be copying the functionality of the search bar, but wouldn’t be able to replicate its history, or autocomplete, or search suggestions.

**Comment by EntilZha** [comment]
True, if it were possible to bring it into focus that would be ideal

**Comment by dbmrq** [comment]
In case anybody's interested, I added this to my `.hammerspoon/init.lua` and it binds `:` to the address bar and `/` to search:

``` lua

hotkey.bind({"shift"}, ';', function()
    local app = hs.application.frontmostApplication()
    local element = hs.uielement.focusedElement():role()
    if app:name() == "Safari" and not string.find(element, "Text") then
        hs.eventtap.keyStroke({"cmd"}, "l")
    else
        hs.eventtap.keyStrokes(':')
    end
end)

hotkey.bind({}, '/', function()
    local app = hs.application.frontmostApplication()
    local element = hs.uielement.focusedElement():role()
    if app:name() == "Safari" and not string.find(element, "Text") then
        hs.eventtap.keyStroke({"cmd"}, "f")
    else
        hs.eventtap.keyStrokes('/')
    end
end)
```

Seems to be working very well.

**Comment by gggritso** [comment]
Looks like Hammerspoon is a better tool for this. I’m going to close this issue and post your example instructions in [the wiki](https://github.com/gggritso/Vimmy.safariextension/wiki) for visibility. Thank you for investigating this and posting a solution!
