### ISSUE TITLE
User settings for key bindings

### ISSUE THREAD

**Issue by martinbohman** [gggritso/Vimmy.safariextension#42]
It would be useful if the user could choose the key bindings.

Things like scroll distance and hint characters would be nice as well.

**Comment by gggritso** [comment]
Closing this is a dupe of #21. Please see my comments on that issue, which I still stand by.

**Comment by martinbohman** [comment]
Ah ok, my bad. I only checked for open issues so I missed that one. Thanks for letting me know!
