### ISSUE TITLE
vimmy commands override textbox

### ISSUE THREAD

**Issue by irvannotaqi** [gggritso/Vimmy.safariextension#43]
i have find myself unable to comment on forums and youtube videos because the character are used in vimmy commands. is there anyway to get around this? thanks

**Comment by gggritso** [comment]
Wow, good question. YouTube chose to implement their input box in a completely unsemantic way, so there isn’t a good way for me to detect that you’re in a text box at all. Shame on them ... I’m not sure I can help you there. What other sites is it broken on?

**Comment by irvannotaqi** [comment]
wow, didnt know that. the other one is a website ran by my faculty at scele.cs.ui.ac.id . I don't think you can do anything about it either as if I recall correctly you need account provided by the faculty to be able to comment on forums.

**Comment by gggritso** [comment]
I’m going to close this issue for now. Please re-open if more information appears, or if changes to YouTube go through.
