### ISSUE TITLE
Allow a count when using tab navigation commands

### ISSUE THREAD

**Issue by xaviervalarino** [gggritso/Vimmy.safariextension#44]
A possible enhancement for your consideration:

I sometimes find myself wanting to be able to go navigate multiple tabs forwards or backwards and wish I could use a count when using the navigation commands, *e.g.*, `3gt` or `3K` to go three tabs to the right.

**Comment by gggritso** [comment]
This seems only somewhat useful, and kind of a pain to implement because of edge-cases. I’ll leave the issue open to contributors, but I won’t be tackling it myself anytime soon, sorry.

**Comment by gggritso** [comment]
Closing for now due to lack of support.
