### ISSUE TITLE
Allow customizing of link hint letters

### ISSUE THREAD

**Issue by eproxus** [gggritso/Vimmy.safariextension#47]
I'm using a Dvorak layout and would find customization of the link hint letters very useful. This is possible in Vimium and Vimperator among other similar extensions.

**Comment by gggritso** [comment]
This one’s a no-brainer, it should definitely be a setting. I’ll put it in the next release.

**Comment by gggritso** [comment]
🎉

**Comment by eproxus** [comment]
Just tried it out, and it seems like some characters are included even though they're not in the list. I set my list to `hutenosaidmkgp` but `j` gets used anyway.

**Comment by gggritso** [comment]
Hm, can you double-check please? I can’t reproduce this locally at all.

**Comment by eproxus** [comment]
Seems it might have been related to page reloads, once reloading the affected pages the link hints seems correct. Thanks again for the feature and for looking into it! ❤️
