### ISSUE TITLE
Typo: ctrl-d to move down "have" a page

### ISSUE THREAD

**Issue by mk2soldier** [gggritso/Vimmy.safariextension#49]
Only one minor thing I've noticed on the extension website (http://gggritso.com/Vimmy.safariextension/)

Edit:
I didn't want to open another issue for this but I've also noticed that using the "f" command on the same website the "home" link isn't available to keyboard navigation, no hint character appears near the yellow text..
Maybe I'm missing something

Thank you for the great extension BTW 👍

**Comment by gggritso** [comment]
Fixed and fixed, thank you!
