### ISSUE TITLE
add a command for new tab

### ISSUE THREAD

**Issue by dyonroot** [gggritso/Vimmy.safariextension#50]
I have been using chrome on mac for a long time just because vimium, and I switched to safari immediately after I found this awesome extension.

but after using this extension for a few days, I found that there is no command for `new tab`, and I'm used to opening a new tab with command `t`. However, I can simply open a new tab with `⌘-t`, but that just not the Vim way. 

so, is that possible to add a new command (e.g. `t`) for new tab?

**Comment by gggritso** [comment]
Just to clarify, does Vimium already have a `t` shortcut to open a new tab? I’m usually happy to copy Vimium behaviour, but I don’t like introducing brand new behaviour.

**Comment by dyonroot** [comment]
Thanks for your reply!
Yes, the Vimium does have a `t` shortcut to open a new tab. Check out the `Manipulating tabs` part of the vimium help page.
![Vimium Help Page](http://imgur.com/AjaYJJK.jpg)
