### ISSUE TITLE
Add a command for undo close tab

### ISSUE THREAD

**Issue by qianzhangxa** [gggritso/Vimmy.safariextension#51]
First of all, thanks for making this awesome extension!!!

Can you please add a command (like "u") to undo close tab? Vimium also has such command.

**Comment by kniziol** [comment]
My proposition is:
`X` because `x` is used to close, so inverted, large "X" will undo close.

**Comment by gggritso** [comment]
PR has been attempted, but it’s difficult to make it work correctly for a lack of access to the right browser APIs. Only `cmd+shift+t` can ensure correct behaviour, and I don’t want to add a partially-broken feature. Closing for now.

**Comment by kniziol** [comment]
I've found solution:

The _Tab Options_ plugin
http://canisbos.com/taboptions
