### ISSUE TITLE
Change the behavior of "h" and "l"

### ISSUE THREAD

**Issue by qianzhangxa** [gggritso/Vimmy.safariextension#52]
Can you please change the behavior of "h" and "l" from scroll left/right to switch to left/right tab which is the also the behavior of Vimium?

**Comment by gggritso** [comment]
Oooh, I’m a little nervous about this. Technically there is already existing behaviour here and I wouldn’t want to change it for people. That said, I can’t imagine many people are using `h` and `l` anyway...

**Comment by gggritso** [comment]
Closing for now due to lack of support.
