### ISSUE TITLE
Keep hints enabled 

### ISSUE THREAD

**Issue by sandersantema** [gggritso/Vimmy.safariextension#54]
Is there any way to keep hints enabled? Or could this be implemented? For instance it could be implemented so that if you press f twice hints would stay enabled. If you're doing something repetitive this is very handy, instead of having to press f al the time. Anyways thanks for the awesome extension.

**Comment by gggritso** [comment]
What I’m going to do is always keep the hints open if using `shift+f` to open in new tabs, and always close them if using just `f`. To me, that makes sense in 95% of cases, and seems like a good solution. We can revisit in the future.
