### ISSUE TITLE
Seems like blacklisted domains function is not working

### ISSUE THREAD

**Issue by zky999** [gggritso/Vimmy.safariextension#57]
I configured Vimmy 0.9.1 not to response any shortcut keys on trello.com, but Vimmy still intercepted the keyboard events. Safari version is 10.1.1 (12603.2.4). Please advice.

![screenshot](https://user-images.githubusercontent.com/2784820/27570561-bdd37092-5b31-11e7-96fc-8325225d0457.jpg)

**Comment by gggritso** [comment]
You need to escape the slash. Try `trello.com\/.*` :)

**Comment by zky999** [comment]
@gggritso Working like a charm! Thank you!
