### ISSUE TITLE
'esc' exit focus mode.

### ISSUE THREAD

**Issue by mayqiyue** [gggritso/Vimmy.safariextension#6]
Hello. Thx for the powerful extension. But can you add a function: use 'esc' to exit focus mode?

**Comment by gggritso** [comment]
Sorry, what do you mean by “focus mode”?

**Comment by mayqiyue** [comment]
Sorry~ In other word maybe easier to understand.
For example: editing mode of HTML's input element (With the cursor blinking).

**Comment by gggritso** [comment]
Mmm, I don’t know about this, it really seems like a browser feature more than a Vimmy thing. Thoughts?

**Comment by gggritso** [comment]
This issue hasn’t gotten much attention. I maintain that this is outside the scope of this extension, so I’m closing the issue as such.
