### ISSUE TITLE
Add shortcut to open copied url

### ISSUE THREAD

**Issue by kniziol** [gggritso/Vimmy.safariextension#60]
`p` shortcut will be nice to open in current tab
`P` shortcut will be nice to open in new tab
(like in Vimium for Google Chrome)

**Comment by gggritso** [comment]
Hm, from what I can see Safari extensions don’t have access to the clipboard, so I don’t think I can be of much help here ... could you be able to do some digging and see how the Chrome extension accomplishes this?

**Comment by kniziol** [comment]
Nope. Sorry :)

**Comment by gggritso** [comment]
Fair enough. This is really low-priority for me, and I don’t really feel like looking into it. It’s a non-trivial feature, for sure. If someone else wants to take a look, I’d be happy to help.

**Comment by gabrielarpino** [comment]
Second this! Would be useful.

**Comment by gggritso** [comment]
I looked around for a while, and right now Safari doesn’t support clipboard access for extensions, so I cannot tackle this. Sorry!
