### ISSUE TITLE
Remove focus from all elements using Ctrl-[ or escape

### ISSUE THREAD

**Issue by bipvanwinkle** [gggritso/Vimmy.safariextension#61]
With previous vim-like browser extensions that I've used it has been possible to remove focus from all browser elements in order to issue vim commands. I really like having this feature. Is it possible with Safari? If so, I'd be happy to take a crack at it and present a pull request. I'd likely need a little mentoring, but I'm happy to do the heavy lifting.

**Comment by gggritso** [comment]
Hm, we already have this feature actually. For example, in this exact field if I type `esc` the field is unfocused and I can issue commands. Did you find spots where it doesn’t work properly? Are you using the latest version of the extension?

**Comment by bipvanwinkle** [comment]
I should have been more precise. ESC does indeed remove focus from input fields, but not the search bar (omnibar). Also in full screen mode ESC first exists full screen mode and then if pressed again will remove focus from the input field. If possible it would be nice to be able to use Ctrl-[ (a common Vim shortcut for ESC) to exit from input fields and the search bar (omnibar).

What do you think? Is this possible? Would you be interesting in guiding me in adding this feature?

**Comment by gggritso** [comment]
Unfortunately it is not possible right now :( Safari extension key listeners live _inside the page itself_. If the keyboard focus isn’t inside the page I can’t listen to the keyboard. Sorry! If this changes at some point, I would be 100% on board.
