### ISSUE TITLE
Not all links are recognized

### ISSUE THREAD

**Issue by matthjes** [gggritso/Vimmy.safariextension#62]
Hi,

I have several web pages where Vimmy does not recognize all links:

<img width="431" alt="screen shot 2017-07-11 at 11 53 33" src="https://user-images.githubusercontent.com/1440866/28062876-a3d0d834-662f-11e7-80a2-b2b855ce86e8.png">

There is a link at the line starting with "Journalisten" that is not recognized / for which no hint is shown.

**Comment by gggritso** [comment]
I need the URL of the pages to check the markup.

**Comment by gggritso** [comment]
Closing due to lack of information.
