### ISSUE TITLE
Add ability to change link opening behaviour by usage of Shift

### ISSUE THREAD

**Issue by rymndhng** [gggritso/Vimmy.safariextension#63]
In Vimium, you can change the behaviour of link opening by holding down `shift` when typing in the hint. So for example, if there's a hint `FD`, I would expect typing:

`f d` to open the link in the current tab
`F D` would open the link in a new tab

When there is ambiguity I would expect the presence of a shift press on the last character to open in a new tab.

**Comment by gggritso** [comment]
Well, `F d` will open the link in a new tab. Why hold shift the whole time?

**Comment by rymndhng** [comment]
Ah, the idea is you don't need to hold shift the entire time. You only need to hold shift for the last character (in the case of pages with many links)

**Comment by gggritso** [comment]
That's reasonable. I’ll schedule this and put it into the next patch version.
