### ISSUE TITLE
Add option to use d and u rather than ctrl-d and Ctrl-u (like vimium)?

### ISSUE THREAD

**Issue by gabrielarpino** [gggritso/Vimmy.safariextension#65]

**Comment by gggritso** [comment]
This one’s interesting. I generally like adding shortcuts that Vimium already has, but I do _not_ like adding shortcuts that have a different meaning in Vim. I want the same habits to work between both applications. Thoughts? How important is this?

**Comment by gabrielarpino** [comment]
OH I see, forgot about the actual vim standards. I got used to the d and u from vimium, but it has happened to me that I press u in vim to try to scroll up and it deletes a bunch of my stuff. Maybe add an option to use shift-u rather than ctrl-u then? Because on the new Macs ctrl is a bit annoying to have to hit every time, shift is easier. Hopefully there isn't a command already taken for shift-u.

**Comment by amarendra** [comment]
I think the point is user can change it to whatever they like. Is it possible? 

(Making a full time move to Safari and looking for a VimFx replacement)

**Comment by gggritso** [comment]
It’s possible but it’d be quite a lot of work for me, and I’m not very motivated since I’d never use it myself. If someone wants to take a stab at it, I’m happy to give some advice, though.

**Comment by amarendra** [comment]
That's okay.

Found https://github.com/flipxfx/sVim and https://github.com/guyht/vimari. will check if there are more or I can just work with these. I need just few controls is all but I usually change the default ones.

Thanks.

**Comment by gggritso** [comment]
Closing for now. User-customizable mappings are a complicated feature and is out-of-scope for now. Will wait for more use-cases.
