### ISSUE TITLE
Add excluded keys to settings

### ISSUE THREAD

**Issue by ogirginc** [gggritso/Vimmy.safariextension#67]
Right now, you can only blacklist a website and disable whole keys. However, there are cases where excluding a single key would be very useful.

For example, `t` is used to start fuzzy finder for Github. To use it, you have to blacklist the website and lose all of the shortcuts.

Vimium has this functionality:

<img width="869" alt="screen shot 2017-08-28 at 10 20 28" src="https://user-images.githubusercontent.com/7466873/29763164-a82d798e-8bda-11e7-8830-33bc2d47a8c2.png">

**Comment by gggritso** [comment]
Reasonable request, but to support this properly I’d have to at the very least:
- add a brand-new out-of-Safari settings UI
- add a settings management system for the extension
- add in-extension ability to ignore individual keys

This is quite a bit of work! I don’t know whether I’ll have time to work on this in the near future, but I’ll leave the issue open in case someone else is able and willing to step up.

**Comment by ogirginc** [comment]
Thanks! 👍

**Comment by gggritso** [comment]
This project is officially abandonware and is not accepting any PRs or issues. This extension will stop working as of macOS Catalina. Sorry, and thank you, but mostly sorry!
