### ISSUE TITLE
Settings revert after some page reloads

### ISSUE THREAD

**Issue by eproxus** [gggritso/Vimmy.safariextension#68]
After updating to 0.11, the settings seems to revert after a few page reloads on different sites. The settings seems to revert to the default. The hint characters stays the same, but from that point on changing any settings has no effect.

**Comment by gggritso** [comment]
That’s very strange, sorry about that! I’m having some trouble reproducing this though, can you provide more specific steps?

**Comment by eproxus** [comment]
Sorry, I'm not using the extension anymore at the moment. I'll close this for now.
