### ISSUE TITLE
'j' stopped working in Reader mode

### ISSUE THREAD

**Issue by ogirginc** [gggritso/Vimmy.safariextension#69]
For some reason, <kbd>j</kbd> stopped working properly when I am using it in Reader mode.

![reader-mode](https://user-images.githubusercontent.com/7466873/31008322-607f64f8-a50c-11e7-934f-2f44873e2b64.gif)

or in [Giphy](http://www.giphy.com/gifs/3ohhwukVeRELPARlYI)

**Comment by gggritso** [comment]
Interesting! I’m on High Sierra right now, and Reader mode actually has its own `jk` scrolling, which knows about paragraphs and images. Neat! What OS and Safari are you on?

**Comment by ogirginc** [comment]
Sorry! I am using Sierra 10.12.6 with Safari 11.0.

**Comment by ogirginc** [comment]
Also just realized, this doesn't happen for every website like [this one](http://www.asymco.com/2017/10/02/silicon-valley/). Weird. ¯\\_(ツ)_/¯

**Comment by ogirginc** [comment]
It seems, most of the issues happen when the reader mode is activated in a subdomain of blogspot.

**Comment by gggritso** [comment]
It looks like on High Sierra, extensions don’t fire in Reader View at all! I wonder if that’s new...

**Comment by gggritso** [comment]
I’m going to close this for lack of activity. If this is still open, please let me know.
