### ISSUE TITLE
Is it possible to add the navigation or searching key

### ISSUE THREAD

**Issue by giveflow** [gggritso/Vimmy.safariextension#71]
In vim, there is a key `\` to prompt vim searching a relevant content after `\`.

But `\` does not exit in Vimmy. Although the bulit-in safari key ( `cmd + f` ) works at some point, it is impossible for me to hand on the keyboard while picking the next matched content and etc.

**Comment by gggritso** [comment]
Sorry but this is really difficult. Triggering browser actions like searching is something that’s outside the scope of this extension.
