### ISSUE TITLE
using D and U instead of Ctrl-D and Ctrl-U

### ISSUE THREAD

**Issue by TangMonk** [gggritso/Vimmy.safariextension#72]
It is more convient without press two bottoms , just like Vimium in chrome

**Comment by gggritso** [comment]
I generally like giving people Vimium behaviour, but I’m also worried about changing behaviours that already exist, and deviating from Vim. I’m going to leave this open just for a bit, to make sure no one has issues with this.

**Comment by karimknaebel** [comment]
I think, best would be to have both C-d and d do the same.

**Comment by rachidcalazans** [comment]
I prefer ctrl-d to simulate the vim and avoid to press by mistake

**Comment by karimknaebel** [comment]
@rachidcalazans it's not tragic when you press it by mistake, you won't do anything irreversible. Also with the same argumentation you could hit `hjkl` by mistake. I don't think it's a valid reason.

**Comment by dgrnbrg** [comment]
I would like this feature, or the ability to customize the key bindings.

**Comment by gggritso** [comment]
This project is officially abandonware and is not accepting any PRs or issues. This extension will stop working as of macOS Catalina. Sorry, and thank you, but mostly sorry!
