### ISSUE TITLE
While using key f to start this rep, page jump to star members page？

### ISSUE THREAD

**Issue by itibbers** [gggritso/Vimmy.safariextension#77]
Instead of star this rep, the page jump to the other page, is it normal or bug ?

**Comment by gggritso** [comment]
Hm, I was not able to reproduce this. Could you provide some details about your browser and the exact page you were on?

**Comment by gggritso** [comment]
This project is officially abandonware and is not accepting any PRs or issues. This extension will stop working as of macOS Catalina. Sorry, and thank you, but mostly sorry!
