### ISSUE TITLE
Focus is given to new tab when opening links using shift-f

### ISSUE THREAD

**Issue by jpulgarin** [gggritso/Vimmy.safariextension#78]
In Safari 11, focus is immediately given to the new tabs opened using shift-f. If I understand correctly, the desired behaviour is for the links to open in a new tab in the background.

**Comment by jpulgarin** [comment]
I was able to fix this by enabling and then disabling 'Immediately activate new tabs' in the extension settings.

**Comment by gggritso** [comment]
Thank you for reporting this, it looks like there’s some kind of error with loading extension settings. I filed a new issue: #79
