### ISSUE TITLE
How do I update to v0.3.0?

### ISSUE THREAD

**Issue by florianbeer** [gggritso/Vimmy.safariextension#8]
Hi,
I am currently running v0.2 and seem to be unable to update to the latest Vimmy version. Safari Extension gallery is just showing me "installed", but no update notification and  if I download the file directly from the URL in `updateManifest.plist` (https://s3.amazonaws.com/gggritso.com/Vimmy.safariextz) Safari won't let me install the package:

![screen shot 2016-08-16 at 08 34 59](https://cloud.githubusercontent.com/assets/800047/17690060/58e2e96c-638c-11e6-9d58-666275876099.png)

OSX Version: 10.11.6 (15G31)
Safari Version: 9.1.2 (11601.7.7)

**Comment by gggritso** [comment]
Bizarre! I will take a look ASAP. Sorry for the delay, I’m quite busy these days.

**Comment by florianbeer** [comment]
No worries, you're providing free software here. There's zero pressure!

**Comment by Traxmaxx** [comment]
You need to uninstall the current version. Then open the downloaded `Vimmy.safariextz` and  Safari shows the following:
<img width="597" alt="screen shot 2016-09-02 at 19 30 48" src="https://cloud.githubusercontent.com/assets/320272/18212490/df1c392e-7143-11e6-9620-71a9f627d0b4.png">
Then choose whatever you prefer : )

**Comment by florianbeer** [comment]
Ace! That worked like a charm.  
Thank you!

**Comment by gggritso** [comment]
Thanks @Traxmaxx!
