### ISSUE TITLE
New tab opens with empty page

### ISSUE THREAD

**Issue by ghost** [gggritso/Vimmy.safariextension#80]
When using `t` key, new tabs open with empty page, ignoring Safari's preferences. For example, if I set new tabs to open with Homepage in Safari, `cmd+t` works correctly whereas `t` doesn't. 

IMO this is important because Vimmy's key bindings don't work on empty pages (which AFAIK is limitation of extensions).

Two solutions come to mind:
1. inherit Safari's settings (I couldn't find whether that is possible)
2. add new tab default url to Vimmy's settings

**Comment by gggritso** [comment]
Ooh, interesting! You are correct that Vimmy bindings are limited to open pages. You are also correct that inheriting Safari’s settings is not possible, so, yes, adding a default open URL might be the only way to address this one. I will look into this.

**Comment by gggritso** [comment]
This project is officially abandonware and is not accepting any PRs or issues. This extension will stop working as of macOS Catalina. Sorry, and thank you, but mostly sorry!
