### ISSUE TITLE
[BUG] Text boxes aren't always recognized, makes commands randomly activate while typing

### ISSUE THREAD

**Issue by LP0101** [gggritso/Vimmy.safariextension#81]
This happens rather infrequently, but mostly happens on things such as browser-based VNC viewers. Typing becomes impossible as any shortcut will trigger the action (ie - typing 't' will open a new tab)

**Comment by gggritso** [comment]
Interesting! What’s the most specific example you can provide? This is a hard one to track down

**Comment by starbase527** [comment]
I’ve also noticed this problem, particularly on mailing list management pages such as

https://lists.archlinux.org/listinfo/arch-announce
and
https://mailman.ntg.nl/mailman/listinfo/ntg-context

**Comment by gggritso** [comment]
This project is officially abandonware and is not accepting any PRs or issues. This extension will stop working as of macOS Catalina. Sorry, and thank you, but mostly sorry!
