### ISSUE TITLE
Unable to use drop-down menus

### ISSUE THREAD

**Issue by factotvm** [gggritso/Vimmy.safariextension#83]
Steps to Reproduce

1. Visit https://www.google.com/search?source=hp&q=foobar
2. Hit "f" to show link hints
3. Type the hint for "Tools"

Expected

* The drop down is displayed (allowing subsequent navigation via another press of "f")

Actual

* No drop down is displayed

Notes

There is another Vim browser extension I use on another browser. I'd love to stop using that browser all  together, but this feature is so important. That extension is: https://vimium.github.io/

**Comment by gggritso** [comment]
This project is officially abandonware and is not accepting any PRs or issues. This extension will stop working as of macOS Catalina. Sorry, and thank you, but mostly sorry!
