### ISSUE TITLE
Error in macOS Mojave

### ISSUE THREAD

**Issue by karimknaebel** [gggritso/Vimmy.safariextension#84]
In macOS Mojave, every time Safari is opened, it complains that it can't install vimmy. Vimmy is working as expected though.

**Comment by gggritso** [comment]
Uh oh! My computer is too old to even install Mojave on it, so I’m gonna have trouble testing this one. Could you take a screenshot of the error message for me?

**Comment by karimknaebel** [comment]
Will do, I think I found the error though. The old Javascript Safari extensions are being deprecated in favor of native Mac Apps as Safari extensions. Therefore for now one should just install safari extensions from the gallery.

**Comment by gggritso** [comment]
😟

**Comment by ogirginc** [comment]
Fyi, this isn't a problem of MacOS version. APIs changed with Safari 12, which is available for Sierra, High Sierra & Mojave.

**Comment by gggritso** [comment]
Yeah I actually installed Safari 12 locally and it’s 🎉 busted. I’ll take a look at this, but if someone here actually knows their way around XCode and wants to take this over that’d be 👌🏻

**Comment by jpulgarin** [comment]
Vimmy version 0.11.0 (installed from the Extensions Gallery) works perfectly on Safari 12 by the way.

**Comment by gggritso** [comment]
This project is officially abandonware and is not accepting any PRs or issues. This extension will stop working as of macOS Catalina. Sorry, and thank you, but mostly sorry!
