### ISSUE TITLE
yank links

### ISSUE THREAD

**Issue by caleb5baird** [gggritso/Vimmy.safariextension#85]
Feature Request: 
add the ability to copy a link using the 'f' feature. 

Propose 'yf' to enter link mode but when a link is selected it will be copied to the clipboard rather than opened.

**Comment by benjamin-rood** [comment]
Both yank functions, in fact:

`yy`      to yank (copy) the URL of the current page into the clipboard
`yf`      to yank (copy) a link URL to the clipboard

After link opening, this is the most useful feature from Vimium.
Would be good to know how hard this would be to implement?

**Comment by gggritso** [comment]
This project is officially abandonware and is not accepting any PRs or issues. This extension will stop working as of macOS Catalina. Sorry, and thank you, but mostly sorry!
