### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by deshearth** [gggritso/Vimmy.safariextension#86]
Could you make the scrolling smoother?

**Comment by gggritso** [comment]
😂 yes probably, but I really don’t feel like it! I’ll look into it if/when I ever get to re-doing this extension for Mojave as an App Extension 😢 

Dupe of #76, #64 and #28

**Comment by gggritso** [comment]
This project is officially abandonware and is not accepting any PRs or issues. This extension will stop working as of macOS Catalina. Sorry, and thank you, but mostly sorry!
