### ISSUE TITLE
Revisit approach for form input fields

### ISSUE THREAD

**Issue by rubenvarela** [gggritso/Vimmy.safariextension#87]
Just stumbled upon #31 again. The input field is,

```<input type="input" class="otherinput" name="email" value="" placeholder="Type in your email address" autocomplete="off">```

#31 was closed by expanding to allow more valid input types. Of course, not everyone uses valid ones. 

I know that it was mentioned that a better way to handle it might be needed. Maybe even removing the check altogether. 

I wanted to open this as a placeholder for discussion around that.

**Comment by gggritso** [comment]
Dang! I think the thing to do is to revise https://github.com/gggritso/Vimmy.safariextension/blob/master/src/vimmy2.js#L304

My first instinct is that instead of checking for that list of greedy input types, it should mark _all_ `input` elements as capturing keys

**Comment by rubenvarela** [comment]
I gave it some thought yesterday I can't think of any con to it. 

If they wanted to execute a Vimmy command, they could hit Esc to loose focus of the field.

**Comment by gggritso** [comment]
Are you open to submitting a PR for the fix? It’s a small one!

**Comment by rubenvarela** [comment]
Sure thing!

**Comment by gggritso** [comment]
This project is officially abandonware and is not accepting any PRs or issues. This extension will stop working as of macOS Catalina. Sorry, and thank you, but mostly sorry!
