### ISSUE TITLE
Install from source?

### ISSUE THREAD

**Issue by dgrnbrg** [gggritso/Vimmy.safariextension#88]
Hi, I'd like to make some modifications to Vimmy & install it. How do I build or install it myself?

**Comment by gggritso** [comment]
I think the [Extension Builder](https://developer.apple.com/library/archive/documentation/Tools/Conceptual/SafariExtensionGuide/UsingExtensionBuilder/UsingExtensionBuilder.html) documentation will have the information you need!

**Comment by gggritso** [comment]
This project is officially abandonware and is not accepting any PRs or issues. This extension will stop working as of macOS Catalina. Sorry, and thank you, but mostly sorry!
