### ISSUE TITLE
Vimmy commands override textbox (continuation)

### ISSUE THREAD

**Issue by patrickshox** [gggritso/Vimmy.safariextension#89]
As some other people have mentioned, like #43, Vimmy commands will open a new tab instead of typing "t". Here's an example website that's giving me issues:
https://duke.qualtrics.com/jfe/form/SV_23NCol5nO8luuxe?Q_JFE=qdg

**Comment by gggritso** [comment]
This project is officially abandonware and is not accepting any PRs or issues. This extension will stop working as of macOS Catalina. Sorry, and thank you, but mostly sorry!
