### ISSUE TITLE
Input mode to temporarily disable keybindings

### ISSUE THREAD

**Issue by 0x0blu** [gggritso/Vimmy.safariextension#90]
Now we only have the option to disable Vimmy for whole websites permanently.

I propose that an input mode is used to disable all the keybindings except for the escape button that gets out of that mode.

**Comment by gggritso** [comment]
This project is officially abandonware and is not accepting any PRs or issues. This extension will stop working as of macOS Catalina. Sorry, and thank you, but mostly sorry!
